### PR TITLE
Issue #64: Build Linux ARM64 image in addition to x86_64 (for GHCR)

### PR DESCRIPTION
**Pull request by martin-g**
Build weekly images with ARM64

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

### CODE REVIEW

**Review by almahmoud — APPROVED** [review]
I reverted the changes for the weekly build script as it will require a bit more changes, and added some slight changes to the GHCR build to take into account that the base rocker tags used for `amd64` (`devel`) do not support `arm64`, so switching tag out for `latest` which does support `arm64`.
This will result in an experimental build for GHCR only, which I believe is a good first testing image before changing Docker auto-build configuration, and the weekly build next.

**Comment by martin-g** [comment]
@almahmoud I see a problem in the changes you made with https://github.com/Bioconductor/bioconductor_docker/pull/67/commits/398c0938f2051497cf5839bf7f17c6da4246c0a8
Now the VMs/runners build separate images for each platform and the last one wins/overwrites. 
See https://github.com/su2code/SU2/pkgs/container/SU2%2Fbuild-su2/60410181?tag=221224-1158 - at the top you can see that the image has two architectures (`OS / Arch 2`).
There is no such label/tab at https://github.com/Bioconductor/bioconductor_docker/pkgs/container/bioconductor/63025835?tag=RELEASE_3_16
And indeed if I start a container on my x86_64 dev machine I see:
```
$ docker run -it --rm ghcr.io/bioconductor/bioconductor:RELEASE_3_16
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
...
```

There is no such warning on my aarch64 machines.
I.e. the image is `linux/arm64` only, not multi-platform one.

**Comment by almahmoud** [comment]
@martin-g I noticed that and have been trying to figure out how to get different bases but still build at the same time, and I came up with this: https://github.com/Bioconductor/bioconductor_docker/commit/f10853b8249022b8ff89392b678668e8a8803081

Which seems to work in theory on my machine, will follow-up a bit later on the actual builds, hopefully this should solve it though.
Let me know if you know of any other less hacky ways of accomplishing a different base image depending on arch.

**Comment by martin-g** [comment]
I've added few comments to the commit.
I think it would be simpler by using `matrix.include` (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-expanding-configurations)

**Comment by almahmoud** [comment]
Yeh I'm not sure it can be done via matrix and still build both images at the same time, unless there is a way to push them separately but keep both. The TARGETARCH var is set automatically for multi-platform builds, and it did work (https://github.com/Bioconductor/bioconductor_docker/actions/runs/3907157873). Happy to take suggestions for another way of doing it, but this seems to work for now.
image

P.S.: The latest code is in branch `RELEASE_3_16` since there is no arm64 rocker image for Rdevel yet. I will proceed to rename the `master` branch `devel` and update code there next week.

**Pull request merged**
